FROM confluentinc/cp-kafka-connect:latest

USER root

# Установка необходимых пакетов
RUN yum install -y curl && yum clean all

# Скачивание и установка S3 коннектора
RUN curl -L -o /tmp/s3-connector.zip \
    "https://d1i4a15mxbxib1.cloudfront.net/api/plugins/confluentinc/kafka-connect-s3/versions/10.6.4/confluentinc-kafka-connect-s3-10.6.4.zip" && \
    confluent-hub install --no-prompt /tmp/s3-connector.zip && \
    rm /tmp/s3-connector.zip

USER appuser